---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install CLI Tools
      package:
        name:
          - bat
          - tmux
          - vim
          - zsh
    - name: Copy Configs
      copy:
        src: configs/
        dest: ~/