---
- hosts: localhost
  connection: local

  tasks:
    - name: Add GPG Keys
      become: true
      ansible.builtin.rpm_key:
        key: "{{ item }}"
        state: present 
      loop:
        - 'https://packages.microsoft.com/keys/microsoft.asc'
      
    - name: Add Repositories
      become: true
      ansible.builtin.copy:
        src: 'repos/'
        dest: '/etc/yum.repos.d/'

    - name: Install Tools
      become: true
      package:
        name:
          - bat
          - tmux
          - vim
          - zsh
          - powerline-fonts
          - code
        state: 'present'

    - name: Install Flatpaks

    - name: Copy Configs
      copy:
        src: configs/
        dest: ~/

    - name: Clone oh-my-zsh
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: ~/.oh-my-zsh
    
    - name: Change Shell
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh