---
- name: Add GPG Keys for Fedora
  become: true
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present 
  loop:
    - 'https://packages.microsoft.com/keys/microsoft.asc'
    - 'https://rpm.releases.hashicorp.com/gpg'
  when: ansible_facts['distribution'] == "Fedora"

- name: Add GPG Keys for Ubuntu
  become: true
  ansible.builtin.apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - 'https://packages.microsoft.com/keys/microsoft.asc'
    - 'https://apt.releases.hashicorp.com/gpg'
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Add Repositories
  become: true
  ansible.builtin.copy:
    src: 'repos/'
    dest: '/etc/yum.repos.d/'
  when: ansible_facts['distribution'] == "Fedora"

- name: Add Ubuntu Repositories
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
  loop: 
    - 'deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main'
    - 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-{{ ansible_lsb.codename }}-prod {{ ansible_lsb.codename }} main'
  when: ansible_facts['distribution'] == "Ubuntu"
  notify: updateAptCache

- name: Add Flathub
  become: true
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: 'https://flathub.org/repo/flathub.flatpakrepo'
    state: present
  when: ansible_facts['distribution'] == "Fedora"

- name: Install Tools
  become: true
  package:
    name:
      - bat
      - tmux
      - vim
      - zsh
      - code
      - terraform
      - latte-dock
    state: 'present'

- name: Install Ubuntu Tools
  become: true
  package:
    name:
      - fonts-powerline
      - docker
      - docker-compose
      - azure-functions-core-tools-4
    state: 'present'
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install Fedora Tools
  become: true
  package:
    name:
      - powerline-fonts
      - podman
      - podman-compose
    state: 'present'
  when: ansible_facts['distribution'] == "Fedora"

- name: Enable and Start Services
  become: true
  ansible.builtin.systemd:
    name: '{{ item }}'
    enabled: true
  loop:
    - podman
  when: ansible_facts['distribution'] == "Fedora"

- name: Enable and Start Services
  become: true
  ansible.builtin.systemd:
    name: '{{ item }}'
    enabled: true
  loop:
    - docker
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install Flatpaks
  community.general.flatpak:
    name:
      - com.getpostman.Postman
    state: present
  when: ansible_facts['distribution'] == "Fedora"

- name: Install Snaps
  become: true
  community.general.snap:
    name:
      - postman
      - slack
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install VS Code Extensions
  become: false
  ansible.builtin.command:
    cmd: 'code --install-extension {{ item }}'
    creates: '~/.vscode/extensions/{{ item }}*'
  loop:
    - ms-azuretools.vscode-docker
    - ms-azuretools.vscode-azurefunctions
    - ms-azuretools.vscode-cosmosdb
    - ms-dotnettools.csharp
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - pkief.material-icon-theme
    - redhat.ansible
    - redhat.vscode-yaml
    - vscodevim.vim
    - zhuangtongfa.material-theme
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Copy Configs
  become: false
  copy:
    src: configs/
    dest: ~/

- name: Clone oh-my-zsh
  become: false
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    
- name: Modify User Account
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - docker
    append: yes
    shell: /bin/zsh
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Modify User Account
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - wheel
    append: yes
    shell: /bin/zsh
  when: ansible_facts['distribution'] == "Fedora"