---
- name: Determine Tasks for Workstation
  ansible.builtin.include_tasks:
    file: "{{ tasks }}"
  loop:
    - "./os/Ubuntu.yml"
  loop_control:
    loop_var: tasks
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Determine Tasks for Workstation
  ansible.builtin.include_tasks:
    file: "{{ tasks }}"
  loop:
    - "./os/Fedora.yml"
  loop_control:
    loop_var: tasks
  when: ansible_facts['distribution'] == "Fedora"
