---
- name: Add GPG Keys
  become: true
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present 
  loop:
    - 'https://packages.microsoft.com/keys/microsoft.asc'
    - 'https://rpm.releases.hashicorp.com/gpg'
      
- name: Add Repositories
  become: true
  ansible.builtin.copy:
    src: 'repos/'
    dest: '/etc/yum.repos.d/'

- name: Add Flathub
  become: true
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: 'https://flathub.org/repo/flathub.flatpakrepo'
    state: present

- name: Install Tools
  become: true
  package:
    name:
      - bat
      - tmux
      - vim
      - zsh
      - powerline-fonts
      - code
      - terraform
      - podman
      - podman-compose
    state: 'present'

- name: Enable and Start Services
  become: true
  ansible.builtin.systemd:
    name: '{{ item }}'
    enabled: true
  loop:
    - podman

- name: Install Flatpaks
  community.general.flatpak:
    name:
      - com.getpostman.Postman
    state: present

- name: Install VS Code Extensions
  ansible.builtin.command:
    cmd: 'code --install-extension {{ item }}'
    creates: '~/.vscode/extensions/{{ item }}*'
  loop:
    - ms-dotnettools.csharp
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - pkief.material-icon-theme
    - redhat.ansible
    - redhat.vscode-yaml
    - vscodevim.vim
    - zhuangtongfa.material-theme

- name: Copy Configs
  copy:
    src: configs/
    dest: ~/

- name: Clone oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    
- name: Change Shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh