---
- name: Add GPG Keys for Fedora
  become: true
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present
  loop:
    - 'https://packages.microsoft.com/keys/microsoft.asc'
    - 'https://rpm.releases.hashicorp.com/gpg'

- name: Add Repositories
  become: true
  ansible.builtin.copy:
    src: 'repos/'
    dest: '/etc/yum.repos.d/'
    mode: 0664

- name: Add Flathub
  become: true
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: 'https://flathub.org/repo/flathub.flatpakrepo'
    state: present

- name: Install Tools
  become: true
  ansible.builtin.package:
    name:
      - git
      - bat
      - tmux
      - vim
      - zsh
      - code
      - dotnet-sdk-3.1
      - dotnet-sdk-6.0
      - terraform
      - latte-dock
      - powerline-fonts
      - podman
      - podman-compose
      - python3
      - python-is-python3
      - pip
      - ansible
      - virt-manager
    state: 'present'

- name: Install Python Packages
  ansible.builtin.pip:
    name:
      - ansible-lint

- name: Enable and Start Services
  become: true
  ansible.builtin.systemd:
    name: '{{ item }}'
    enabled: true
    state: started
  loop:
    - podman
    - libvirtd

- name: Install Flatpaks
  community.general.flatpak:
    name:
      - com.getpostman.Postman
    state: present

- name: Install VS Code Extensions
  become: false
  ansible.builtin.command:
    cmd: 'code --install-extension {{ item }}'
    creates: '~/.vscode/extensions/{{ item }}*'
  loop:
    - ms-azuretools.vscode-docker
    - ms-azuretools.vscode-azurefunctions
    - ms-azuretools.vscode-cosmosdb
    - ms-dotnettools.csharp
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - pkief.material-icon-theme
    - redhat.ansible
    - redhat.vscode-yaml
    - vscodevim.vim
    - zhuangtongfa.material-theme

- name: Copy Configs
  become: false
  ansible.builtin.copy:
    src: configs/
    dest: ~/
    mode: 0664

- name: Clone oh-my-zsh
  become: false
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    version: master

- name: Modify User Account
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - wheel
      - libvirt
      - libvirt-qemu
    append: true
    shell: /bin/zsh
