---
- name: Add GPG Keys for Ubuntu
  become: true
  ansible.builtin.apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - 'https://packages.microsoft.com/keys/microsoft.asc'
    - 'https://apt.releases.hashicorp.com/gpg'

- name: Add Ubuntu Repositories
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - 'deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main'
    - 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-{{ ansible_lsb.codename }}-prod {{ ansible_lsb.codename }} main'
    - 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
    - 'deb [arch=amd64] https://packages.microsoft.com/{{ ansible_distribution | lower }}/{{ ansible_distribution_version }}/prod
      {{ ansible_lsb.codename }} main'
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install Tools
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - git
      - bat
      - tmux
      - tree
      - vim
      - zsh
      - code
      - dotnet-sdk-6.0
      - terraform
      - latte-dock
      - fonts-powerline
      - podman
      - azure-functions-core-tools-4
      - python3
      - python-is-python3
      - python3-venv
      - pip
      - virt-manager
    state: 'present'

- name: Enable and Start Services
  become: true
  ansible.builtin.systemd:
    name: '{{ item }}'
    enabled: true
    state: started
  loop:
    - libvirtd

- name: Install Snaps
  become: true
  community.general.snap:
    name:
      - postman
      - slack
    state: present

- name: Modify User Account
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - libvirt
      - libvirt-qemu
    append: true
    shell: /bin/zsh
